// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"cadcore_equipment_guardsman_helmet_base", \
"cadcore_equipment_guardsman_helmet_ws", \
"cadcore_equipment_guardsman_uniform_base", \
"cadcore_equipment_guardsman_vest_recruit", \
"cadcore_equipment_guardsman_vest_base", \
"cadcore_equipment_guardsman_vest_medic", \
"cadcore_equipment_guardsman_vest_assault", \
"cadcore_equipment_guardsman_vest_marksman"

#define UNIT_LIST \
"cadcore_equipment_guardsman_unit_base"
