// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"baw_equipment_battledroid_helmet_base", \
"baw_equipment_battledroid_uniform_base", \
"baw_equipment_battledroid_uniform_woodland", \
"baw_equipment_battledroid_uniform_crew", \
"baw_equipment_battledroid_uniform_pilot", \
"baw_equipment_battledroid_uniform_sec", \
"baw_equipment_battledroid_uniform_sec_cpl", \
"baw_equipment_battledroid_uniform_marine", \
"baw_equipment_battledroid_uniform_eng", \
"baw_equipment_battledroid_uniform_firefighter", \
"baw_equipment_battledroid_uniform_abd", \
"baw_equipment_battledroid_uniform_mksm_base", \
"baw_equipment_battledroid_uniform_mksm_abd", \
"baw_equipment_battledroid_Plating_Basic", \
"baw_equipment_battledroid_Plating_Advanced"

#define UNIT_LIST \
"baw_equipment_battledroid_backpack_base", \
"baw_equipment_battledroid_backpack_rto", \
"baw_equipment_battledroid_backpack_antenna", \
"baw_equipment_battledroid_backpack_RTO_Clear", \
"baw_equipment_battledroid_backpack_droppack", \
"baw_equipment_battledroid_backpack_fortify", \
"baw_equipment_battledroid_unit_base", \
"baw_equipment_battledroid_unit_woodland", \
"baw_equipment_battledroid_unit_crew", \
"baw_equipment_battledroid_unit_pilot", \
"baw_equipment_battledroid_unit_sec", \
"baw_equipment_battledroid_unit_sec_cpl", \
"baw_equipment_battledroid_unit_marine", \
"baw_equipment_battledroid_unit_eng", \
"baw_equipment_battledroid_unit_firefighter", \
"baw_equipment_battledroid_unit_abd", \
"baw_equipment_battledroid_unit_mksm_base", \
"baw_equipment_battledroid_unit_mksm_abd", \
"baw_equipment_battledroid_helmet_base_GH", \
"baw_equipment_battledroid_uniform_base_GH", \
"baw_equipment_battledroid_uniform_woodland_GH", \
"baw_equipment_battledroid_uniform_crew_GH", \
"baw_equipment_battledroid_Plating_Basic_GH", \
"baw_equipment_battledroid_Plating_Advanced_GH"
