// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_HEADGEAR(baw_equipment_battledroid_helmet_base,"[BAW] Battledroid Interface");
MACRO_GH_UNIFORM(baw_equipment_battledroid_uniform_base,"[BAW] Battledroid");
MACRO_GH_UNIFORM(baw_equipment_battledroid_uniform_woodland,"[BAW] Battledroid (Woodland)");
MACRO_GH_UNIFORM(baw_equipment_battledroid_uniform_crew,"[BAW] Crew Battledroid");
MACRO_GH_VEST(baw_equipment_battledroid_Plating_Basic,"[BAW] B1 Battledroid Plating");
MACRO_GH_VEST(baw_equipment_battledroid_Plating_Advanced,"[BAW] B1 Battledroid Plating (OOM)");
