// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"baw_equipment_commando_uniform_base", \
"baw_equipment_commando_uniform_stealth", \
"baw_equipment_commando_vest_base"

#define UNIT_LIST \
"baw_equipment_commando_unit_base", \
"baw_equipment_commando_unit_stealth_base", \
"baw_equipment_commando_uniform_base_GH"
