// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_UNIFORM(baw_equipment_commando_uniform_base,"[BAW] BX-Commando Chassis");
